changelog:
  exclude:
    authors:
      - pre-commit-ci
  exclude-labels:
    - 'skip-changelog'
    - 'no-changelog-entry-needed'
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
