language: c
os:
 - linux
 - osx
env:
 matrix:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
 global:
  - CONDA_DEPENDENCIES="nodejs numpy nomkl jupyterlab>=0.34"
  - CONDA_CHANNELS="conda-forge"
  - CONDA_CHANNEL_PRIORITY=True
  - SETUP_XVFB=True

# matrix:
#   allow_failures:
#     env: PYTHON_VERSION=3.6

before_install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda info -a

install:
  - pip install -e .[test]

script:
  - pytest --cov glue_jupyter glue_jupyter
  - pip install astroquery pyyaml
  - python .validate-notebooks.py

after_success:
  - codecov
