resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name: 'pypi_endpoint'
    test_extras: test
    test_command: pytest --pyargs glue_jupyter
    targets:
    - sdist
    - wheels_universal

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    - linux: codestyle
      libraries: {}
      coverage: 'false'

    - linux: py36-test-devdeps
    - linux: py37-test-devdeps

    - macos: py36-test-devdeps
    - macos: py37-test-devdeps

    - windows: py36-test-devdeps
    - windows: py37-test-devdeps

    - linux: py37-notebooks-devdeps
    - macos: py37-notebooks-devdeps
    - windows: py36-notebooks-devdeps

    - linux: py37-docs-devdeps
    - macos: py37-docs-devdeps
    - windows: py36-docs-devdeps
