name: glue-jupyter
dependencies:
  - pyqt
  - nomkl
  - nodejs
  - pip:
    - jupyterlab
    - ipywidgets
    - ipympl
    - https://github.com/glue-viz/glue/archive/master.zip
    - https://github.com/glue-viz/glue-vispy-viewers/archive/master.zip
