name: glue-jupyter
channels:
  - glueviz/label/dev
  - conda-forge
dependencies:
  - glue-core
  - glue-vispy-viewers
  - pip
  - jupyterlab >=0.32
  - ipywidgets
  - ipympl
  - nomkl
# these are for now installed from git master in postBuild
#  - bqplot
#  - ipyvolume
